# Generated by Django 3.1.6 on 2021-02-27 17:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_auto_20210227_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='follow',
        ),
        migrations.AddField(
            model_name='user',
            name='follow',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userfollow', to=settings.AUTH_USER_MODEL),
        ),
    ]
