# Generated by Django 3.1.6 on 2021-02-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_auto_20210227_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='useradmin',
            field=models.IntegerField(),
        ),
    ]
